version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/yolo_model.pt:/app/yolo_model.pt
    restart: always

  build_frontend_assets:
    build: ./frontend

  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
        - ./frontend/dist:/usr/share/nginx/html:ro
        #- /etc/letsencrypt/live/tomitik.ru:/etc/nginx/ssl:ro
        #- /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
        - /etc/letsencrypt/:/etc/letsencrypt/:ro
      depends_on:
        - backend
      restart: always # Make sure Nginx restarts if it crashes