version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/yolo_model.pt:/app/yolo_model.pt
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    expose:
      - "80"
    environment:
      - VITE_API_URL=http://188.225.45.142:5000
    restart: always

nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro
    depends_on:
      - frontend
      - backend