# docker build -f Dockerfile.base -t yolo-base:latest .
FROM python:3.10-slim

WORKDIR /base

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.shared.txt .
RUN pip install --no-cache-dir -r requirements.shared.txt
